### ISSUE TITLE
Please add mass editor to all sounds in a playlist

### ISSUE THREAD

**Issue by apoapostolov** [Mallander/playlist-enhancer#1]
The mass editor would allow to change their volume (slider with value field), their fade duration, their play mode, etc.

**Comment by Mallander** [comment]
Hey @apoapostolov , thanks for the feedback! Sounds like a cool idea, I'll look into it!

**Comment by Mallander** [comment]
This is coming in the next release. At first it will allow you to edit track specific metrics such as:

Volume
Fade
Repeat

For all tracks in a playlist.

Playback method is set on a playlist level rather than track level and already edited via the core "Edit Playlist" so if you have any more thoughts on that one let me know!

**Comment by Mallander** [comment]
@apoapostolov From a user perspective, how would you like the "defaults" for bulk sound editing to work?

Currently, it will grab the settings from the first tracks in the playlist which works well especially in the case of a bulk song edit being done in the past. Would you expect this behaviour?

Also, regarding the application of the settings there may be cases where you only want to update a single feature of the tracks, as a user would you expect:

A: Checkbox options for each setting of if you want to apply it
B: Only apply if setting has changed from the default loaded
C: Other (Please elaborate)

Hopefully I can get it working how you'd prefer to use it, rather than a half-baked method!

**Comment by apoapostolov** [comment]
* Right click on a Playlist - Bulk Editor
* Open a dialog where I can set Volume, Fade Duration, and Repeat mode. These values should use the last used default rather than take from any song in the playlist. If a default is not saved, it's OK to use the value of the first sound in the playlist. 
* Container that contains list of every sound in the playlist, with a checkbox at the front. You can check in several, or press Select All to select all to apply to the whole playlist.
* Two buttons at the bottom. Bulk Update and Save as Default. Bulk Update does what it says, applies the above settings to all selected songs (several or all via Select All). Save as Default remembers the above options so next time the Dialog is opened, the values will remember what was set as default rather than take the values from any song from within the playlist.

**Comment by Mallander** [comment]
Thanks for the feedback!

The initial MVP will be as your minimum mentioned:

Bulk edit all sounds in a playlist to edit volume, fade and loop.

But I'll also look to include the saved defaults option in the MVP too depending on how much work that takes initially, if not in the first release it will be in the second.

I'll expand the UI as a future enhancement to allow for more user control over the bulk changes per sound.

**Comment by Mallander** [comment]
@apoapostolov The initial version of Bulk Sound editing has been released, allowing you to edit:

Volume
Fade
Repeat

For all tracks in a playlist. This also includes default settings that you can set yourself using the "Save defaults" button for the future.

This is accessed by right-clicking on a playlist and choosing "Bulk Edit Sounds".

Your feedback on the feature is most welcome! :)

**Comment by apoapostolov** [comment]
I checked it and it works excellent. Thank you so much!

**Comment by Mallander** [comment]
Great! I'll close this issue for now, but please raise more for any extra features you want added. I've noted your requests from this issue regarding final functionality.
